M48
; DRILL file {KiCad (6.0.7)} date Sun Feb  5 18:06:48 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-02-05T18:06:48+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C2.000
%
G90
G05
T1
X82.804Y-64.008
X82.804Y-115.316
X163.576Y-64.516
X163.576Y-115.316
T0
M30
